name:  Accounts - develop
on:
  push:
    branches:
      - master
jobs:
  scan:
    name: SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SCA Scan
        uses: snyk/actions@master
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: docker build
        working-directory: ./microservices/section4/accounts
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=docker.io/mariammishu/accounts:latest

      - name: docker login
        run:
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: docker push
        run: docker push docker.io/mariammishu/accounts:latest